### PR TITLE
Optimised Images

### PR DESCRIPTION
**Pull request by agarwalutkarsh554**

### CODE REVIEW

**Comment by srevinsaju** [comment]
@agarwalutkarsh554 can you explain the changes associated with this PR, the benefits to aslo, etc.?

**Comment by agarwalutkarsh554** [comment]
The size of all the images have been reduced by atleast 50% and that to without any loss in quality.

**Comment by quozl** [comment]
No, the total size change is about 14%.  What tool is used to verify that there is no difference in the rendered images?

**Comment by chimosky** [comment]
@agarwalutkarsh554 do you intend to keep working on this?

**Comment by chimosky** [comment]
Closing this as stale.

**Pull request closed without merging**
