### PR TITLE
Remove SFC reference, update to current version of our blurb

### PR DESCRIPTION
**Pull request by pikurasa**

### CODE REVIEW

**Comment by pikurasa** [comment]
This only changes the text in the footer, and, I expect, would have no impact on how the code is run. So I don't know why the test would fail. Maybe these tests need to be updated? Or the code needs to be updated?

**Comment by quozl** [comment]
I agree, not a reason not to merge.

@srevinsaju, @chimosky any ideas?  Does anything have to be done to the automation?

**Comment by srevinsaju** [comment]
Nothing blocking the merge. The actions are failing due to new formatting rules from black, which wasn't pinned to a specific version - and another test is failing trying to get a translation file from an XO if I understand correctly. We can merge this PR. Deployment is manual on sunjammer, and it shouldn't cause any errors there.

**Comment by chimosky** [comment]
> Thanks.
> 
> Perhaps we can write a new issue for fixing the test failing.

This sounds good.

**Pull request merged**
